#!/usr/bin/env node

import { mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { build } from 'esbuild';

const output = resolve('native/cocos-poc/assets/generated/frontier-core.ts');
await mkdir(dirname(output), { recursive: true });

// Creator 对 assets 外的 TS 相对导入解析规则更严格；在门禁阶段确定性打成一个
// assets 内模块，既保留唯一源码，也避免为迁就引擎批量改写 Web 端 import。
await build({
  entryPoints: [resolve('src/runtime/cocos-core.ts')],
  outfile: output,
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  banner: { js: '// @ts-nocheck\n// Generated by tools/build_cocos_core.mjs. Do not edit.' },
  logLevel: 'silent',
});

console.log(`[build_cocos_core] wrote ${output}`);
