import { build } from 'esbuild';
import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const target = path.join(root, 'native/godot');
const built = await build({
  stdin: {
    contents: [
      "export * from './src/core/actions.ts';",
      "export * from './src/core/enemies.ts';",
      "export * from './src/core/stages.ts';",
      "export * from './src/core/level.ts';",
      "export * from './src/core/upgrades.ts';",
    ].join('\n'),
    resolveDir: root, loader: 'ts',
  }, bundle: true, format: 'esm', platform: 'node', write: false,
});
const source = await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`);
// 迁移期从旧版导出数值真值；Godot 运行时只读 JSON，不加载 JS 或复制一套 TS 引擎。
const actions = Object.fromEntries(Object.keys(source.ACTIONS).map(id => [id, source.resolveAction(id, 'swift')]));
const sheets = {};
await mkdir(path.join(target, 'data'), { recursive: true });
await mkdir(path.join(target, 'assets/art'), { recursive: true });
for (const [id, name] of Object.entries({ hero: 'hero-v2', grunt: 'enemy-grunt-v2', boss: 'enemy-boss-v2' })) {
  const metadata = JSON.parse(await readFile(path.join(root, `public/art/${name}.json`), 'utf8'));
  sheets[id] = { path: `res://assets/art/${name}.png`, rows: metadata.rowOrder, columns: metadata.columns, baseline: metadata.baseline };
  await copyFile(path.join(root, `public/art/${name}.png`), path.join(target, `assets/art/${name}.png`));
}
const upgrades = Object.fromEntries(['offense', 'arcane', 'guardian'].map(id => [id, {
  label: source.UPGRADE_TRACKS[id].label, description: source.UPGRADE_TRACKS[id].describe(1),
  stats: source.computeUpgradeStats({ offense: 0, arcane: 0, guardian: 0, [id]: 1 }),
}]));
await writeFile(path.join(target, 'data/first_stage.json'), JSON.stringify({
  schema: 1, source: 'src/core; generated by tools/export_godot_data.mjs',
  tick_rate: source.TICK_RATE, player_actions: actions, enemy_actions: source.ACTIONS,
  enemies: source.ENEMY_PROFILES, stage: source.STAGES[0], arenas: source.ROOM_SIZES,
  sheets, upgrades,
}, null, 2) + '\n');
console.log('Godot: exported first-stage rules and 3 original sprite sheets');
